In [2]:
data_dir = '/Users/sadegh.mohammadi/Desktop/real-toy-dataset.csv'
import pandas as pd

# Load Excel file
df = pd.read_csv(data_dir)

# Show first 5 rows
df.head()

,STUDYID,USUBJID,BW_d1,BW_d7,BW_d14,BW_d21,BW_d28,LB_Eosinophils_L,LB_Erythrocytes_L,LB_HCT_BLOOD,...,OM_SPLEEN,OM_LIVER,OM_HEART,STRAIN,SEX,YEAR,ROUTE,GLPFL,TRTVCAT,COMPANY
0,1,1-1001,236.0,298.0,353.0,400.0,416.0,0.20,7.55,44.2,...,0.986,15.120,1.357,SPRAGUE DAWLEY,M,2020,ORAL GAVAGE,Y,AQUEOUS,OTHER
1,1,1-1002,199.0,253.0,302.0,347.0,369.0,0.12,8.31,48.2,...,0.704,12.451,1.333,SPRAGUE DAWLEY,M,2020,ORAL GAVAGE,Y,AQUEOUS,OTHER
2,1,1-1003,246.0,315.0,372.0,428.0,455.0,0.08,8.38,47.5,...,0.757,16.138,1.396,SPRAGUE DAWLEY,M,2020,ORAL GAVAGE,Y,AQUEOUS,OTHER
3,1,1-1005,302.0,358.0,406.0,468.0,499.0,0.10,8.08,47.3,...,0.831,18.750,1.633,SPRAGUE DAWLEY,M,2020,ORAL GAVAGE,Y,AQUEOUS,OTHER
4,1,1-1006,273.0,322.0,350.0,387.0,408.0,0.06,9.20,52.2,...,0.881,13.054,1.441,SPRAGUE DAWLEY,M,2020,ORAL GAVAGE,Y,AQUEOUS,OTHER

data_dir = '/Users/sadegh.mohammadi/Desktop/real-toy-dataset.csv'
import pandas as pd

# Load Excel file
df = pd.read_csv(data_dir)

# Show first 5 rows
print(df.head())